### ISSUE TITLE
fastlane-plugin-applivery repository

### ISSUE THREAD

**Issue by CesarTrigo** [fastlane-community/.github#1]
Hi all,
This is an issue to request the opening of a new repository to host the [current Applivery fastlane plugin](https://github.com/applivery/fastlane-applivery-plugin). Maybe a fork would be useful.

**Repository name:** fastlane-plugin-applivery (based on the other repositories nomenclature)
**Admins:**
- @Alesete
- @CesarTrigo

Thank you,
C.

**Comment by joshdholtz** [comment]
@CesarTrigo Thanks for the request! Let's definitely get this in here 😊 You _should_ be able to go into the settings in your repository and request a transfer into the `fastlane-community`. I then should get an email to accept the transfer 🤞 Once transferred, I'll make sure that you and @Alesete both main admin access to the repo 🙌

**Comment by joshdholtz** [comment]
@CesarTrigo @Alesete I invited you both into a team in this org. You _should_ be able to transfer it in here now that you are apart of this team (hopefully) 🤞

**Comment by CesarTrigo** [comment]
Hi @joshdholtz, thank you for your quick response and guidance.
It seems that I can transfer the ownership of the repo to `fastlane-community` which is great! 

However I'm just concern about something: once transferred, wll fastlane users continue being able to install the plugin via `fastlane add_plugin applivery` or is there any other further action we should perform from our side to re-enable that.

Thank you!

**Comment by joshdholtz** [comment]
@CesarTrigo Everything will still work as is 👌 There are no changes that users will need to do. Rubygems does not need to know anything about where the repo lives. The only thing is on next gem release we will need to update the git repo location in the gemspec meta data but that won't effect users at all. And github will auto redirect to the new repo if somebody goes to the previous url  💪 So everything will still be 💯 for users and won't require any changes really on anyone

**Comment by CesarTrigo** [comment]
Hi @joshdholtz 
Thank you for the clear reply! I just transferred [the repository](https://github.com/fastlane-community/fastlane-applivery-plugin) :tada:. I believe it would be great to rename it to `fastlane-plugin-applivery` but I can't since now I don't have enough permissions over it :worried:. Can you please assist or grant me access?
Thank you!

**Comment by joshdholtz** [comment]
@CesarTrigo Renamed! And now both you and @Alesete should have "Admin" level access now too on that repo 👌

**Comment by CesarTrigo** [comment]
Thank you @joshdholtz for all the support! I believe that everything is good so we can close this thread if you agree :)

**Comment by joshdholtz** [comment]
Not problem at all! Glad you have you both in this community and looking forward to working together on things 😊

**Comment by joshdholtz** [comment]
@CesarTrigo @Alesete I just realized that I don't think we gave me permission to push new versions 🙃 Are you able to add `me@joshholtz.com` to Rubygems? 😇

**Comment by Alesete** [comment]
Hi @joshdholtz ! I've added you as owner along with César and me in Rubygems (https://rubygems.org/gems/fastlane-plugin-applivery)

Greetings!
