### ISSUE TITLE
fastlane-plugin-validate_app

### ISSUE THREAD

**Issue by thii** [fastlane-community/.github#2]
I no longer use this and it looks like it still has _fastlane_ users.

**Comment by janpio** [comment]
Huh, why did you close these issues? Not interested any more?

**Comment by thii** [comment]
I thought there were no interests in taking over them, since the issues didn’t get any reply for more than a week. I can reopen them if you want.

**Comment by janpio** [comment]
You should definitely keep them open until you get an answer - either no or yes. A week is really nothing in OSS land - as you probably know yourself ;)

**Comment by joshdholtz** [comment]
@thii We can reopen these! I was actually going to get to these this afternoon 😇

**Comment by joshdholtz** [comment]
The repo - https://github.com/thii/fastlane-plugin-validate_app

**Comment by thii** [comment]
Thanks @janpio and @joshdholtz. Let me know if you want to take these repos.

**Comment by joshdholtz** [comment]
@thii We would love to take these repos! I'm going to add you to this org so that you can transfer. And if you could add `me@joshholtz.com` to Rubygems that would be 💯

**Comment by thii** [comment]
Done.
