### ISSUE TITLE
fastlane-plugin-carthage_cache

### ISSUE THREAD

**Issue by thii** [fastlane-community/.github#3]
I no longer use this and it looks like it still has _fastlane_ users.

**Comment by joshdholtz** [comment]
The repo - https://github.com/thii/fastlane-plugin-carthage_cache

**Comment by joshdholtz** [comment]
@thii I'm going to add you to this org so that you can transfer. And if you could add `me@joshholtz.com` to Rubygems that would be 💯

**Comment by thii** [comment]
Done.
