### ISSUE TITLE
fastlane-plugin-get_current_swift_version

### ISSUE THREAD

**Issue by thii** [fastlane-community/.github#4]
I no longer use this and it looks like it still has _fastlane_ users.

**Comment by joshdholtz** [comment]
The repo - https://github.com/thii/fastlane-plugin-get_current_swift_version

**Comment by joshdholtz** [comment]
@thii I'm going to add you to this org so that you can transfer. And if you could add `me@joshholtz.com` to Rubygems that would be 💯

**Comment by thii** [comment]
Done (This hasn't been published as a Rubygem).
