### ISSUE TITLE
fastlane-ftp-plugin

### ISSUE THREAD

**Issue by PoissonBallon** [fastlane-community/.github#5]
I no longer use this and no time to maintain it,
But it looks like it still has fastlane users.

url : https://github.com/PoissonBallon/fastlane-ftp-plugin

**Comment by joshdholtz** [comment]
@PoissonBallon Thanks for initially making this plugin 😊 This is definitely a good one to keep maintained. I'm going to add you to this org so that you can transfer. And if you could add `me@joshholtz.com` to Rubygems that would be 💯

**Comment by PoissonBallon** [comment]
Transfers is ok, and I add you to owner for the gem, 
Keep me update if you need anything and thanks you for your work 👍 💪

**Comment by joshdholtz** [comment]
@PoissonBallon Got it! Thanks for the transfer and will do ❤️
